/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadora;

import java.lang.Math;
/**
 *
 * @author nicole
 */
public class calcu extends javax.swing.JFrame {
    
    /* 3 cadenas: Guardan el primer y segundo número, y la operación a realizar, respectivamente.
     * 1 booleano: Revisa si ya se ocupó un operador aritmético.
       Esto es para saber cuándo se debe borrar la cadena de 'TxtPantalla': cuando se ingresa un número
       inmediatamente después de que se haya seleccionado un operador.
     */
    String memoria1, memoria2, operacion;
    boolean flag = false;
    
    /**
     * Creates new form calcu
     */
    public calcu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TxtPantalla = new javax.swing.JTextPane();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPunto = new javax.swing.JButton();
        btnIgual = new javax.swing.JButton();
        btnMenos = new javax.swing.JButton();
        btnMas = new javax.swing.JButton();
        btnMult = new javax.swing.JButton();
        btnDiv = new javax.swing.JButton();
        btnAC = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnSqrt = new javax.swing.JButton();
        btnLn = new javax.swing.JButton();
        btnX2 = new javax.swing.JButton();
        btnXa = new javax.swing.JButton();
        btnEa = new javax.swing.JButton();
        btnNeg = new javax.swing.JButton();
        btnLog10 = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        btnArcsin = new javax.swing.JButton();
        btnArccos = new javax.swing.JButton();
        btnArctan = new javax.swing.JButton();
        btnAbs = new javax.swing.JButton();
        btnCbrt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TxtPantalla.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(TxtPantalla);

        btn1.setBackground(new java.awt.Color(0, 153, 153));
        btn1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setBackground(new java.awt.Color(0, 153, 153));
        btn2.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setBackground(new java.awt.Color(0, 153, 153));
        btn3.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btn4.setBackground(new java.awt.Color(0, 153, 153));
        btn4.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setBackground(new java.awt.Color(0, 153, 153));
        btn5.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btn6.setBackground(new java.awt.Color(0, 153, 153));
        btn6.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setBackground(new java.awt.Color(0, 153, 153));
        btn7.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setBackground(new java.awt.Color(0, 153, 153));
        btn8.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btn9.setBackground(new java.awt.Color(0, 153, 153));
        btn9.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btn0.setBackground(new java.awt.Color(0, 153, 153));
        btn0.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnPunto.setBackground(new java.awt.Color(153, 204, 255));
        btnPunto.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        btnPunto.setText(".");
        btnPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPuntoActionPerformed(evt);
            }
        });

        btnIgual.setBackground(new java.awt.Color(255, 102, 102));
        btnIgual.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        btnIgual.setText("=");
        btnIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIgualActionPerformed(evt);
            }
        });

        btnMenos.setBackground(new java.awt.Color(153, 204, 255));
        btnMenos.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        btnMenos.setText("-");
        btnMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenosActionPerformed(evt);
            }
        });

        btnMas.setBackground(new java.awt.Color(153, 204, 255));
        btnMas.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        btnMas.setText("+");
        btnMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMasActionPerformed(evt);
            }
        });

        btnMult.setBackground(new java.awt.Color(153, 204, 255));
        btnMult.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        btnMult.setText("*");
        btnMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultActionPerformed(evt);
            }
        });

        btnDiv.setBackground(new java.awt.Color(153, 204, 255));
        btnDiv.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        btnDiv.setText("/");
        btnDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivActionPerformed(evt);
            }
        });

        btnAC.setBackground(new java.awt.Color(255, 102, 102));
        btnAC.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        btnAC.setText("AC");
        btnAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnACActionPerformed(evt);
            }
        });

        btnSin.setBackground(new java.awt.Color(153, 153, 255));
        btnSin.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnSin.setText("sin(x)");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        btnCos.setBackground(new java.awt.Color(153, 153, 255));
        btnCos.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnCos.setText("cos(x)");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnTan.setBackground(new java.awt.Color(153, 153, 255));
        btnTan.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnTan.setText("tan(x)");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        btnSqrt.setBackground(new java.awt.Color(153, 204, 255));
        btnSqrt.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        btnSqrt.setText("√x");
        btnSqrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSqrtActionPerformed(evt);
            }
        });

        btnLn.setBackground(new java.awt.Color(153, 153, 255));
        btnLn.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnLn.setText("ln(x)");
        btnLn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLnActionPerformed(evt);
            }
        });

        btnX2.setBackground(new java.awt.Color(153, 153, 255));
        btnX2.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnX2.setText("x²");
        btnX2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnX2ActionPerformed(evt);
            }
        });

        btnXa.setBackground(new java.awt.Color(153, 153, 255));
        btnXa.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnXa.setText("xª");
        btnXa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXaActionPerformed(evt);
            }
        });

        btnEa.setBackground(new java.awt.Color(153, 153, 255));
        btnEa.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnEa.setText("eª");
        btnEa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEaActionPerformed(evt);
            }
        });

        btnNeg.setBackground(new java.awt.Color(153, 204, 255));
        btnNeg.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        btnNeg.setText("(-)");
        btnNeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNegActionPerformed(evt);
            }
        });

        btnLog10.setBackground(new java.awt.Color(153, 153, 255));
        btnLog10.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnLog10.setText("log_10(x)");
        btnLog10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLog10ActionPerformed(evt);
            }
        });

        btnPi.setBackground(new java.awt.Color(153, 204, 255));
        btnPi.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        btnPi.setText("π");
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });

        btnE.setBackground(new java.awt.Color(153, 204, 255));
        btnE.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        btnE.setText("e");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        btnArcsin.setBackground(new java.awt.Color(153, 153, 255));
        btnArcsin.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnArcsin.setText("arcsin(x)");
        btnArcsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArcsinActionPerformed(evt);
            }
        });

        btnArccos.setBackground(new java.awt.Color(153, 153, 255));
        btnArccos.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnArccos.setText("arccos(x)");
        btnArccos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArccosActionPerformed(evt);
            }
        });

        btnArctan.setBackground(new java.awt.Color(153, 153, 255));
        btnArctan.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnArctan.setText("arctan(x)");
        btnArctan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArctanActionPerformed(evt);
            }
        });

        btnAbs.setBackground(new java.awt.Color(153, 153, 255));
        btnAbs.setFont(new java.awt.Font("Rockwell", 0, 22)); // NOI18N
        btnAbs.setText("abs(x)");
        btnAbs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbsActionPerformed(evt);
            }
        });

        btnCbrt.setBackground(new java.awt.Color(153, 204, 255));
        btnCbrt.setFont(new java.awt.Font("Rockwell", 1, 22)); // NOI18N
        btnCbrt.setText("3√x");
        btnCbrt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCbrtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnArcsin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnArccos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnArctan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLog10, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21)
                                .addComponent(btnXa, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(btn0, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btn2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnNeg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPunto, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnMult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAbs))))
                    .addComponent(jScrollPane1))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAbs, btnArccos, btnArcsin, btnArctan, btnCos, btnEa, btnLn, btnLog10, btnSin, btnTan});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCbrt, btnE, btnMas, btnMenos, btnMult, btnPi, btnPunto, btnSqrt});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnLog10)
                            .addComponent(btnArctan, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAbs)
                            .addComponent(btnEa, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXa, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnArccos)
                            .addComponent(btnArcsin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnX2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnSqrt, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnCbrt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(9, 9, 9)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnMas, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnMult, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnNeg, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnDiv, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnAC, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnIgual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 217, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAbs, btnArccos, btnArcsin, btnArctan, btnCbrt, btnE, btnEa, btnLog10, btnMas, btnMenos, btnMult, btnNeg, btnPi, btnPunto, btnSqrt, btnX2, btnXa});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCos, btnLn, btnSin, btnTan});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // 5
        if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+"5");
        }
        else
        {
            flag=false;
            TxtPantalla.setText("5");
        }
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // 4
        if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+"4");
        }
        else
        {
            flag=false;
            TxtPantalla.setText("4");
        }
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
        // 9
        if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+"9");
        }
        else
        {
            flag=false;
            TxtPantalla.setText("9");
        }
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // 1
        if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+"1");
        }
        else
        {
            flag=false;
            TxtPantalla.setText("1");
        }
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // 2
        if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+"2");
        }
        else
        {
            flag=false;
            TxtPantalla.setText("2");
        }
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // 3
        if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+"3");
        }
        else
        {
            flag=false;
            TxtPantalla.setText("3");
        }
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // 6
        if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+"6");
        }
        else
        {
            flag=false;
            TxtPantalla.setText("6");
        }
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // 7
        if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+"7");
        }
        else
        {
            flag=false;
            TxtPantalla.setText("7");
        }
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        // 8
        if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+"8");
        }
        else
        {
            flag=false;
            TxtPantalla.setText("8");
        }
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        // 0
        if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+"0");
        }
        else
        {
            flag=false;
            TxtPantalla.setText("0");
        }
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPuntoActionPerformed
        // Punto
        if (flag==false)
        {
            if(!TxtPantalla.getText().contains("."))
            {
                TxtPantalla.setText(TxtPantalla.getText()+".");
            }
        } else
        {
            flag = false;
            /* Aquí no hacen falta las condicionales de si 'TxtPantalla' contiene ".", o hacer setText()
               del texto que venía escrito + ".", porque al fin y al cabo, SE ACABA DE BORRAR EL TEXTO
               QUE HABÍA.
             * Por ello, sin preocupación de lo demás, se puede escribir "." por sí solo.
             */
            TxtPantalla.setText(".");
       }
    }//GEN-LAST:event_btnPuntoActionPerformed

    private void btnACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnACActionPerformed
        // AC
        TxtPantalla.setText("");
        // Para que la calculadora no lo tome como si el operador siga en uso.
        operacion = null;
    }//GEN-LAST:event_btnACActionPerformed

    private void btnMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenosActionPerformed
        // Resta
        if(!TxtPantalla.getText().equals(""))
        {
            memoria1=TxtPantalla.getText();
            operacion="-";     
            flag = true;
        }
    }//GEN-LAST:event_btnMenosActionPerformed

    private void btnMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMasActionPerformed
        // Suma
        if(!TxtPantalla.getText().equals(""))
        {
            memoria1=TxtPantalla.getText();
            operacion="+";
            flag = true;
        }
    }//GEN-LAST:event_btnMasActionPerformed

    private void btnMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultActionPerformed
        // Multiplicación
        if(!TxtPantalla.getText().equals(""))
        {
            memoria1=TxtPantalla.getText();
            operacion="*";
            flag = true;
            
        }
    }//GEN-LAST:event_btnMultActionPerformed

    private void btnDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivActionPerformed
        // División
        if(!TxtPantalla.getText().equals(""))
        {
            memoria1=TxtPantalla.getText();
            operacion="/";
            flag = true;         
        }
    }//GEN-LAST:event_btnDivActionPerformed

    private void btnIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIgualActionPerformed
        // Igual
        String resultado;
        memoria2=TxtPantalla.getText();

        try
        {
            // Operaciones Aritméticas + x^y
            if ((operacion=="+")||(operacion=="-")||(operacion=="*")||(operacion=="/")||(operacion=="potencia"))
            {
                resultado = Aritmeticas(memoria1, memoria2, operacion);
                TxtPantalla.setText(resultado);
            }
                 
            /* Otras operaciones:
             * Trigonométricas y Exponenciales
             */
            else if ((operacion=="Cos")||(operacion=="√")||(operacion=="alcuadrado")||(operacion=="eª")||(operacion=="Sin")||(operacion=="Tan")||(operacion=="Ln")||(operacion=="Log10")||(operacion=="Arcsin")||(operacion=="Arccos")||(operacion=="Arctan")||(operacion=="Abs")||(operacion=="Cbrt")||(operacion=="Arcsin"))
            {
                resultado = TrigsYExp(operacion, memoria2);
                TxtPantalla.setText(resultado);
            }                      
        }
        catch (java.lang.NullPointerException e)
        {
            memoria2 = "0";
        }
    }//GEN-LAST:event_btnIgualActionPerformed

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        // cos(x)
            operacion="Cos";
            flag = true;
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnSqrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSqrtActionPerformed
        // Raiz
            operacion="√";
            flag = true;
    }//GEN-LAST:event_btnSqrtActionPerformed

    private void btnXaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXaActionPerformed
        // x^a
            memoria1=TxtPantalla.getText();
            operacion="potencia";
            flag = true;
    }//GEN-LAST:event_btnXaActionPerformed

    private void btnX2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnX2ActionPerformed
        // x^2
            memoria1 = TxtPantalla.getText();
            operacion = "alcuadrado";
            flag = true;
    }//GEN-LAST:event_btnX2ActionPerformed

    private void btnEaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEaActionPerformed
        // e^a
            operacion="eª";
            flag = true;
    }//GEN-LAST:event_btnEaActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        // Sen
            operacion="Sin";
            flag = true;
    }//GEN-LAST:event_btnSinActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        // Tan
            operacion="Tan";
            flag = true;
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnLnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLnActionPerformed
        // Ln
            operacion="Ln";
            flag = true;
    }//GEN-LAST:event_btnLnActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        // Pi
        /*if (flag==false)
        {
            TxtPantalla.setText(TxtPantalla.getText()+String.valueOf(Math.PI));
        }
        else
        {
            flag=false;*/
            TxtPantalla.setText(String.valueOf(Math.PI));
        //}
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        // e
        TxtPantalla.setText(String.valueOf(Math.E));
    }//GEN-LAST:event_btnEActionPerformed

    private void btnNegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNegActionPerformed
        // Negate
       TxtPantalla.setText(String.valueOf(Double.parseDouble(TxtPantalla.getText())*(-1)));
    }//GEN-LAST:event_btnNegActionPerformed

    private void btnLog10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLog10ActionPerformed
        // Log10
        operacion="Log10";
        flag = true;
    }//GEN-LAST:event_btnLog10ActionPerformed

    private void btnArcsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArcsinActionPerformed
        // arcsin(x)
        operacion="Arcsin";
        flag = true;
    }//GEN-LAST:event_btnArcsinActionPerformed

    private void btnArccosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArccosActionPerformed
        // arccos(x)
        operacion="Arccos";
        flag = true;
    }//GEN-LAST:event_btnArccosActionPerformed

    private void btnArctanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArctanActionPerformed
        // arctan(x)
        operacion="Arctan";
        flag = true;
    }//GEN-LAST:event_btnArctanActionPerformed

    private void btnAbsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbsActionPerformed
        // abs
        operacion="Abs";
        flag = true;
    }//GEN-LAST:event_btnAbsActionPerformed

    private void btnCbrtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCbrtActionPerformed
        // Raíz cúbica
        operacion="Cbrt";
        flag = true;
    }//GEN-LAST:event_btnCbrtActionPerformed

    public /*static*/ String Aritmeticas (String memoria1, String memoria2, String operacion)
    {
        //Double resultado=0.0;
        //^Aquí 'resultado' no es un dato de tipo <double>: es un objeto de la clase 'Double'.
         
        double resultado=0.0;
        String respuesta;
        
        switch(operacion)
        {
            case "-": 
                resultado= Double.parseDouble(memoria1)-Double.parseDouble(memoria2);
                break;
                
            case "+":
                resultado= Double.parseDouble(memoria1)+Double.parseDouble(memoria2);
                break;
                
            case "/":
                resultado= Double.parseDouble(memoria1)/Double.parseDouble(memoria2);
                break;
                
            case "*":
                resultado= Double.parseDouble(memoria1)*Double.parseDouble(memoria2);
                break;
                
            case "potencia":
                resultado= Math.pow(Double.parseDouble(memoria1), Double.parseDouble(memoria2));
                break;
                
        }
        //respuesta=resultado.toString();
        /* ^Como 'resultado' es un objeto, y no un dato de tipo <double>, sí aplica el método .toString()
           para convertirlo a tipo String, y así poder publicarlo en TxtPantalla.
         * Sin embargo, por algún motivo el IDE lo marcaba con error (a pesar de que si servía).
         * Así que usar el método String.valueOf(<var de tipo double>) también funcionó (y sin marcar e-
           rror).
         */
        respuesta=String.valueOf(resultado);
        return respuesta;
    }
    
    // Se necesitaba otro método que aceptara sólo 1 "número" (en verdad es un String).
    public String TrigsYExp (String operacion, String memoria1)
    {
        double resultado=0.0;
        String respuesta;
        
        switch(operacion)
        {
            case "√":
                resultado= Math.sqrt(Double.parseDouble(memoria1));
                break;
 
            case "alcuadrado":
                resultado = Math.pow(Double.parseDouble(memoria1), 2);
                break;
                
            case "Sin":
                resultado = Math.round(Math.sin(Math.PI*(Double.parseDouble(memoria1))/180));
                break;
                
            case "Cos":
                resultado = Math.round(Math.cos(Math.PI*(Double.parseDouble(memoria1)/180)));
                break;
                
            case "Tan":
                resultado = Math.round(Math.tan(Math.PI*(Double.parseDouble(memoria1)/180)));
                break;
                
            case "eª":
                resultado = Math.exp(Double.parseDouble(memoria1));
                break;
                
            case "Ln":
                resultado = Math.log(Double.parseDouble(memoria1));            
                break;
            
            case "Log10":
                resultado = Math.log10(Double.parseDouble(memoria1));            
                break;
            
            case "Arcsin":
                resultado = Math.asin(Double.parseDouble(memoria1));
                break;
            
            case "Arccos":
                resultado = Math.acos(Double.parseDouble(memoria1));
                break;
                
            case "Arctan":
                resultado = Math.atan(Double.parseDouble(memoria1));
                break;
            
            case "Abs":
                resultado = Math.abs(Double.parseDouble(memoria1));
                break;
                
            case "Cbrt":
                resultado = Math.cbrt(Double.parseDouble(memoria1));
                break;
        }
        respuesta=String.valueOf(resultado);
        return respuesta;
    }
    
    // Método que checa si se haya ingresado un número irracional: e ó π
    /*public double IrratCheck(String irr)
    {
        String temp;
        double res;
        
        if (irr.contains("e"))
        {
            temp = irr.
            irr = irr.replaceAll("e", String.valueOf(Math.PI));
            resp = 
        }
    }*/
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calcu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calcu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane TxtPantalla;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAC;
    private javax.swing.JButton btnAbs;
    private javax.swing.JButton btnArccos;
    private javax.swing.JButton btnArcsin;
    private javax.swing.JButton btnArctan;
    private javax.swing.JButton btnCbrt;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDiv;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEa;
    private javax.swing.JButton btnIgual;
    private javax.swing.JButton btnLn;
    private javax.swing.JButton btnLog10;
    private javax.swing.JButton btnMas;
    private javax.swing.JButton btnMenos;
    private javax.swing.JButton btnMult;
    private javax.swing.JButton btnNeg;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPunto;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnSqrt;
    private javax.swing.JButton btnTan;
    private javax.swing.JButton btnX2;
    private javax.swing.JButton btnXa;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
